### ISSUE TITLE
ajuda, criar um programa para altomação de frente de loja

### ISSUE THREAD

**Issue by cardosorodrigues** [vaamonde/ccna-v7-200-301#10]
Boa noite, professor.
Estou aqui para iniciar um novo projeto, gostaria muito de sua ajuda, tenho um pequeno mercado e gostaria de ter o controle dos meus produtos, gostaria de implementar um sistema de frente de caixa, espero um retorno, muito obrigado.

**Comment by vaamonde** [comment]
Bom dia, infelizmente essa pergunta não cabe nesse projeto ou tópico, pois esse é um curso de Infraestrutura de TI com foco na Certificação Cisco, não sendo focado para Desenvolvimento.

Não trabalho com desenvolvimento, recomendo o Professor José de Assis (https://www.youtube.com/user/ProfessorJosedeAssis).

Deixarei esse tópico por 5 dias e removerei depois disso, pois está fora do foco desse projeto.
Robson Vaamonde
